spring.application.name=supportdesk-api
server.port=${PORT:8081}

spring.datasource.url=jdbc:h2:mem:supportdesk;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

spring.jackson.serialization.write-dates-as-timestamps=false
app.cors.allowed-origin=http://localhost:4201
